config/routes.rb
Rails.application.routes.draw do
  devise_for :merchants, path:'merchants', controllers: {sessions: "merchants/sessions"}
  devise_for :users, path:'users', controllers: {sessions: "users/sessions"}


  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_user_root
      resources :users do
        resources :buys
      end
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_user_root
    end
  end

  devise_scope :merchant do
    authenticated :merchant do
      root 'home#index', as: :authenticated_merchant_root
      resources :merchants do
        resources :buys
        resources :boxes
      end
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_merchant_root
    end
  end

  resources :merchants , only: [:index, :show] do
    resources :boxes
  end
end

app/models/box.rb
class Box < ApplicationRecord
  belongs_to :merchant
  has_one :buy
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :set_box, only: [:show, :edit, :update, :destroy]

  # GET /boxes
  def index
    @boxes = Box.all
  end

  # GET /boxes/1
  def show
  end

  # GET /boxes/new
  def new
    @box = Box.new
  end

  # GET /boxes/1/edit
  def edit
  end

  # POST /boxes
  def create
    @box = Box.new(box_params)

    if @box.save
      redirect_to @box, notice: 'Box was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /boxes/1
  def update
    if @box.update(box_params)
      redirect_to @box, notice: 'Box was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /boxes/1
  def destroy
    @box.destroy
    redirect_to boxes_url, notice: 'Box was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_box
      @box = Box.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def box_params
      params.require(:box).permit(:title, :description, :amount)
    end
end

app/views/boxes/_form.html.erb
<%= simple_form_for(@box) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :amount %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/boxes/edit.html.erb
<h1>Editing Box</h1>

<%= render 'form', box: @box %>

<%= link_to 'Show', @box %> |
<%= link_to 'Back', boxes_path %>

app/views/boxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Boxes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boxes.each do |box| %>
      <tr>
        <td><%= box.title %></td>
        <td><%= box.description %></td>
        <td><%= box.amount %></td>
        <td><%= link_to 'Show', box %></td>
        <td><%= link_to 'Edit', edit_box_path(box) %></td>
        <td><%= link_to 'Destroy', box, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Box', new_box_path %>

app/views/boxes/new.html.erb
<h1>New Box</h1>

<%= render 'form', box: @box %>

<%= link_to 'Back', boxes_path %>

app/views/boxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @box.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @box.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @box.amount %>
</p>

<%= link_to 'Edit', edit_box_path(@box) %> |
<%= link_to 'Back', boxes_path %>