config/routes.rb
Rails.application.routes.draw do
  devise_for :merchants, path:'merchants', controllers: {sessions: "merchants/sessions"}
  devise_for :users, path:'users', controllers: {sessions: "users/sessions"}


  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_user_root
      resources :users do
        resources :buys
      end
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_user_root
    end
  end

  devise_scope :merchant do
    authenticated :merchant do
      root 'home#index', as: :authenticated_merchant_root
      resources :merchants do
        resources :buys
        resources :boxes
      end
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_merchant_root
    end
  end

  resources :merchants , only: [:index, :show] do
    resources :boxes
  end
end

app/models/buy.rb
class Buy < ApplicationRecord
  belongs_to :user
  belongs_to :box
end

app/controllers/buys_controller.rb
class BuysController < ApplicationController
  before_action :set_buy, only: [:show, :edit, :update, :destroy]

  # GET /buys
  def index
    @buys = Buy.all
  end

  # GET /buys/1
  def show
  end

  # GET /buys/new
  def new
    @buy = Buy.new
  end

  # GET /buys/1/edit
  def edit
  end

  # POST /buys
  def create
    @buy = Buy.new(buy_params)

    if @buy.save
      redirect_to @buy, notice: 'Buy was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /buys/1
  def update
    if @buy.update(buy_params)
      redirect_to @buy, notice: 'Buy was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /buys/1
  def destroy
    @buy.destroy
    redirect_to buys_url, notice: 'Buy was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buy
      @buy = Buy.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def buy_params
      params.require(:buy).permit(:user_id, :box_id)
    end
end

app/views/buys/_form.html.erb
<%= simple_form_for(@buy) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.association :box %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/buys/edit.html.erb
<h1>Editing Buy</h1>

<%= render 'form', buy: @buy %>

<%= link_to 'Show', @buy %> |
<%= link_to 'Back', buys_path %>

app/views/buys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buys</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Box</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buys.each do |buy| %>
      <tr>
        <td><%= buy.user %></td>
        <td><%= buy.box %></td>
        <td><%= link_to 'Show', buy %></td>
        <td><%= link_to 'Edit', edit_buy_path(buy) %></td>
        <td><%= link_to 'Destroy', buy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buy', new_buy_path %>

app/views/buys/new.html.erb
<h1>New Buy</h1>

<%= render 'form', buy: @buy %>

<%= link_to 'Back', buys_path %>

app/views/buys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @buy.user %>
</p>

<p>
  <strong>Box:</strong>
  <%= @buy.box %>
</p>

<%= link_to 'Edit', edit_buy_path(@buy) %> |
<%= link_to 'Back', buys_path %>